terminate called after throwing an instance of 'io::error::can_not_open_file'
  what():  Can not open file "/home/sara/Dropbox/Reaching Study/Gilwoo_Automated_v2/csv_only_manual_inspection/2016_11_24_study_4_Part2_1/2016_11_24_study_4_Part2_1_27509_27818_clean_phase2.csv" because "No such file or directory".
